# Generated by Django 3.0.8 on 2020-07-22 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eats', '0002_auto_20200722_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos', verbose_name='Фоторгафия заведения'),
        ),
    ]
