# Generated by Django 3.0.8 on 2020-07-22 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eats', '0004_auto_20200722_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='latitude',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=10, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='shop',
            name='longitude',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=10, verbose_name='Долгота'),
        ),
    ]
