# Generated by Django 3.0.8 on 2020-07-23 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eats', '0009_auto_20200723_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='calories_sum',
        ),
    ]
