# Generated by Django 3.0.8 on 2020-07-22 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='Owner',
            new_name='owner',
        ),
    ]
