# Generated by Django 3.0.8 on 2020-07-22 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eats', '0005_auto_20200722_1148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='photo',
            new_name='image',
        ),
    ]
