# Generated by Django 3.0.8 on 2020-07-22 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eats', '0006_auto_20200722_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=33, verbose_name='Название')),
                ('calories', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
            ],
            options={
                'verbose_name': 'Ингридиент',
                'verbose_name_plural': 'Ингридиент',
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='Название')),
                ('image', models.ImageField(upload_to='images/dish', verbose_name='Изображение')),
                ('calories_sum', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ingredients', models.ManyToManyField(blank=True, related_name='dishes', to='eats.Ingredient', verbose_name='Ингредиенты')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='eats.Shop', verbose_name='Заведение')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюдо',
            },
        ),
    ]
