# Generated by Django 3.0.8 on 2020-07-24 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eats', '0011_auto_20200724_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='calories',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
